/**
COPYRIGHT 2020 LUKE ZAMBELLA
Encoder keymap source file

This file should be autogenerated by computer software to easily configure
the actions for each encoder.
--------------------------------------------------------------------------------
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

#include "encodermap.h"

/**
 * Action codes for each encoder for each direction that they can move
 * See the action code header file in the TMK core source
 * for more info on what these can be
 */
action_t ENCODERMAP_CLK[ENCODER_COUNT] = {
    AC_A, AC_B, AC_C, AC_D, AC_E, AC_F
};

 action_t ENCODERMAP_CCLK[ENCODER_COUNT] = {
    AC_G, AC_H, AC_I, AC_J, AC_K, AC_L
};